
name: Build and Release

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:
    inputs:
      reason:
        required: false
        default: 'Manual test'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install sysand
        run: pip install sysand

      - name: Build .kpar package
        run: |
          sysand build
          cp output/*.kpar output/sysmod.kpar
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*.kpar
